version: "3.7"

services:
  es03:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
    container_name: es03
    environment:
      ES_JAVA_OPTS: -Xmx1g
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./config/es03/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    networks:
      - esnet

networks:
  esnet:
    external: true
