node:
  name: es02
  master: true
  data: true

http:
  max_content_length: 500mb

discovery.seed_hosts:
  - es01

cluster:
  initial_master_nodes:
    - es01
    - es02
  routing.allocation.disk.threshold_enabled: false
  name: elk-docker-cluster

network.host:
  - es02

bootstrap.memory_lock: true
