node:
  name: es03
  master: false
  data: true

discovery.seed_hosts:
  - es01
  - es02

cluster:
  initial_master_nodes:
    - es01
    - es02
  routing.allocation.disk.threshold_enabled: false
  name: elk-docker-cluster

network.host:
  - es03

bootstrap.memory_lock: true
